# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_baslik2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='baslik2',
        ),
    ]
