# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_baslik2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkinda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
            ],
        ),
    ]
