# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kisa_baslik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='baslik',
            field=models.CharField(max_length=50),
        ),
    ]
