# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170801_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='arka_plan_resmi',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
