# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_arka_plan_resmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='arka_plan_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='resim/'),
        ),
    ]
